services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      # 捕获域名的根路径流量
      - "traefik.http.routers.blog-ui.rule=Host(`blog.ctrlkismet.com`)"
      - "traefik.http.routers.blog-ui.entrypoints=websecure"
      - "traefik.http.routers.blog-ui.tls.certresolver=myresolver" # 使用 Cloudflare 申请证书

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-api
    restart: unless-stopped
    environment:
      - DB_PATH=/data/db/blog.db
      - POSTS_DIR=/data/posts
      - TZ=Asia/Shanghai
    volumes:
      - ${DB_DIR}:/data/db
      - ${POSTS_DIR}:/data/posts:ro
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      # 拦截 /api 前缀的请求
      - "traefik.http.routers.blog-api.rule=Host(`blog.ctrlkismet.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.blog-api.entrypoints=websecure"
      - "traefik.http.routers.blog-api.tls.certresolver=myresolver"
      - "traefik.http.services.blog-api.loadbalancer.server.port=8000"

      - "traefik.http.middlewares.limit-10mb.buffering.maxRequestBodyBytes=10485760"
      - "traefik.http.routers.blog-api.middlewares=limit-10mb"

  artalk:
    image: artalk/artalk-go
    container_name: blog-artalk
    restart: unless-stopped
    volumes:
      - artalk_data:/data
    expose:
      - "23366"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      # 拦截 /artalk 前缀的请求
      - "traefik.http.routers.blog-artalk.rule=Host(`blog.ctrlkismet.com`) && PathPrefix(`/artalk`)"
      - "traefik.http.routers.blog-artalk.entrypoints=websecure"
      - "traefik.http.routers.blog-artalk.tls.certresolver=myresolver"
      - "traefik.http.services.blog-artalk.loadbalancer.server.port=23366"
      # 动态剥离 /artalk 前缀，让后端无感接收
      - "traefik.http.middlewares.strip-artalk.stripprefix.prefixes=/artalk"
      - "traefik.http.routers.blog-artalk.middlewares=strip-artalk"

volumes:
  artalk_data:

networks:
  traefik-proxy:
    external: true